
tasks:
  - init: ./gradlew build



vscode:
  extensions:
    - fwcd.kotlin
    - mathiasfrohlich.Kotlin
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-test
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-maven
