
tasks:
  - init: ./gradlew build
    command: ./gradlew test



vscode:
  extensions:
    - fwcd.kotlin
    - mathiasfrohlich.Kotlin
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - richardwillis.vscode-gradle
    - ritwickdey.LiveServer

