
tasks:
  - init: gradle build
    command: gradle test



vscode:
  extensions:
    - fwcd.kotlin
    - mathiasfrohlich.Kotlin
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - richardwillis.vscode-gradle
    - ritwickdey.LiveServer

